### ISSUE TITLE
Suggestion: Download Better Virus'

### ISSUE THREAD

**Issue by Novationo** [sysengineer13/ServiceNever#1]
I'm a little dumb to make a pull request with this feature, 
but when downloading a "virus" maybe add a .bat file download that will run `shutdown.exe /r /f /t 00` or something similar, because we all know that solves all the known problems in the universe. :)

Edit: did the thing in fork, but does not auto download, auto run, nor download after loading bar is complete.
could probably inspect element on some sketch ass website that has actual virus' to see how it works but i dont care

**Comment by progamer562** [comment]
no i think thats going to way to far

**Comment by Novationo** [comment]
> no i think thats going to way to far

i kinda agree but i thought it would be funny
just gonna close comment since its not a real issue as well
