### ISSUE TITLE
NEED DARK MODE SUPPORT!!!!!!!!!1!!

### ISSUE THREAD

**Issue by ajf8729** [sysengineer13/ServiceNever#36]
THIS SITE IS UNUSABLE WITHOUT DARK MODE THIS IS A SEV A PROD DOWN ALSO MY CAPS LOCK KEY IS BROKEN PLEASE HALP

**Comment by adamgell** [comment]
HURRY UP AND FIX THIS. IT IS TERRIBLE

**Comment by adamgell** [comment]
![image](https://user-images.githubusercontent.com/27519/182430844-d643bb10-caea-4e3d-82cb-e54dd908b622.png)

**Comment by adamgell** [comment]
Please put hair on the website like this cheese 

https://i.redd.it/esh9aggfp5f91.jpg
